### ISSUE TITLE
PCM Support for Android and iOS

### ISSUE THREAD

**Issue by felixjunghans** [bsutton/sounds#16]
**Is your feature request related to a problem? Please describe.**
I would really like to switch from flutter sound to sounds, but I need support for recording and playing PCM (Wav). Is there a plan when this codec will be available in sounds? The Google Speech Api only supports wav and flac and for this reason I need one of these codecs. Sounds also only requires minSdk version 16 and not 24 like flutter sounds, which is one of the main reasons why I would like to switch to sounds.

**Describe the solution you'd like**
PCM / Flac support for Android und iOS (Recording and Playing)

**Additional context**
PCM / Flac support is already available in flutter sounds. Maybe there is a way to merge this into sounds?

**Comment by bsutton** [comment]
My intent is to only provide native recording and audio in the base package.
I've started a second project (sounds_codec) with the intent of providing a package that allows conversion to/from a number of codecs.
By placing the codec in a separate package it keeps the core package small and simple (relatively).

If you want support for pcm/flac I would suggest that you raise the issue in the sounds_codec package.
