### ISSUE TITLE
SoundRecorder Documentation wrong

### ISSUE THREAD

**Issue by zxl777** [bsutton/sounds#19]
- Is the documentation wrong ?
Yes. 
https://github.com/bsutton/sounds/wiki/SoundRecorder

The sample code is handwritten and has not been actually verified.
When I actually ran it, I found two spelling errors that caused it to fail to compile.

In addition, this example cannot actually stop recording. I have to delete recorder.onStopped to recorder.stop().

Can you try to improve the source code of this document and example, thank you.

**Comment by mdkess** [comment]
https://github.com/bsutton/sounds/wiki/SoundRecorder#permissions also has references to `.start()` instead of `.record()` - I suspect this is because of the fork.

**Comment by bsutton** [comment]
Thanks for the feed back.
I've now checked that all the snippets on the recording page compile.

The api was a bit of a moving target when the doco was originally written. 

Any other reviews of the doco would be appreciated.
