### ISSUE TITLE
QuickPlay.fromFile(aacfile, volume: 0.8) do not work.

### ISSUE THREAD

**Issue by zxl777** [bsutton/sounds#20]
Released and Beta version
Unhandled Exception: 'package:sounds/src/sound_player.dart': Failed assertion: line 315 pos 12: 'track != null': is not true.

**Comment by bsutton** [comment]
Cab you provide sample code that reproduces the problem

**Comment by bsutton** [comment]
Close a stale.
Feel free to re-open if you can provide additional information a we are unable to reproduce.
