### ISSUE TITLE
[HELP] Play raw Opus frames from websocket stream

### ISSUE THREAD

**Issue by Wyctus** [bsutton/sounds#24]
Hey, thanks for the great library, I'm really pleased with it! 
I would like to ask for help related to these questions:

I'm streaming from my server raw Opus frames, without OGG or CAF container. Since iOS uses CAF instead of the standard OGG container, I'm trying to play the raw frames, so maybe somehow both of them can play my stream. But if necessary I can encapsulate it in a container. 
Is it possible to play raw Opus? Or somehow play CAF/Opus on Android maybe?

My app receives audio data periodically through the websocket. I would like to redirect this audio stream to the player so it can play it continously. Is it somehow possible?

Thank you very much in advance!

**Comment by bsutton** [comment]
The short answer is I don't know.
At this point I'm not looking to support additional codecs directly within the project.

The idea is that we will only support the codecs that android/ios support natively.
I've done some VERY preliminary work on a sister project 'sounds_codecs' which is intended to provide support for a additional codecs.

**Comment by Wyctus** [comment]
Thank you!

What about playing from a stream or some kind of buffer?

Brett Sutton <notifications@github.com> ezt írta (időpont: 2020. aug. 6.,
Cs 9:44):

**Comment by bsutton** [comment]
You can already play from a buffer.

Streams are being considered but we really need some help if it's going to
happen any time soon

**Comment by Wyctus** [comment]
Buffer support sounds great! 
Could you please show me a basic example? I can't find it anywhere.

Thanks!

**Comment by bsutton** [comment]
Its covered in the doco for Track.

Uint8List buffer = ....
// Load a local audio file and get it as a buffer
Uint8List buffer = (await rootBundle.load('assets/samples/audio.mp3'))
    	.buffer
    	.asUint8List();

Track.fromBuffer(buffer)
QuickPlay.fromTrack(track, volume: 1.0);

**Comment by Wyctus** [comment]
Thank you!
