### ISSUE TITLE
GlobalKey<SoundPlayerUIState>();

### ISSUE THREAD

**Issue by putra4648** [bsutton/sounds#32]
Is key for SoundPlayerUIState missing or moved to other documentation?

**Comment by relf108** [comment]
SoundPlayerUIState doesn't have a global key. To access the state you should be passing a key into one of the SoundPlayerUI constructors (fromLoader or fromTrack). This is common practice.

```
var playerUIKey = GlobalKey<SoundPlayerUIState>(); 
...
widget build(){
return SoundPlayerUI.fromLoader(key : playerUIKey ... );
}

foo {
var playerState = playerUIKey.getState();
}
```

**Comment by putra4648** [comment]
All right then i will try it

**Comment by jenniestrongbow** [comment]
SoundPlayerUIState isnt a type. How to import it? Thanks
