### ISSUE TITLE
Many irrelevant log messages (in 1.0.0.beta.11) and potential fix [BUG]

### ISSUE THREAD

**Issue by jonmountjoy** [bsutton/sounds#33]
## Sounds Version : 

- 1.0.0-beta.11
- iOS emulator

Despite the recent fixes here: https://github.com/bsutton/sounds/issues/27 sounds is still issuing loads of polluting debug messages:

```
entered updateProgress
sending updateProgress: {"duration": "418", "current_position": "83.33333333333333"}
entered updateProgress
sending updateProgress: {"duration": "418", "current_position": "182.6303854875283"}
entered updateProgress
audioPlayerDidFinishPlaying
stopping ProgressTimer
```

## Attempts to fix

* I use `Log.loggingLevel = Level.nothing;` in `main()`. 
* I updated to sounds_common 1.0.8

(Note that beta.11 still uses sounds_common 1.0.6)

## Source of messages

I've tracked the messages down to [Soundplayer.m](https://github.com/bsutton/sounds/blob/master/ios/Classes/SoundPlayer.m).

It has loads of `NSLog` statements.  

These are synchronous calls (so may slow things down), and NSLog has no provision for logging levels.

[Apple's docs](https://developer.apple.com/library/archive/technotes/tn2347/_index.html) suggest hiding them behind a `DEBUG` preprocessor macro.

## Possible solutions

* remove them all
* try and hide them all behind a DEBUG preprocessor macro

**Comment by jonmountjoy** [comment]
(I'm happy to take a stab at either of these)

**Comment by relf108** [comment]
Neither @bsutton nor I have much experience with Objective C so it would be great if you could have a go at this one. The preprocessor solution sounds good to me. On the other hand, the NSLog statements were put in place to debug some of the Objective C code and I think we're beyond that now so go with whichever solution you think is best.
