### ISSUE TITLE
A RenderFlex overflowed by 55 pixels on the right.

### ISSUE THREAD

**Issue by tenSunFree** [bsutton/sounds#42]
Android/HTC U11

A RenderFlex overflowed by 55 pixels on the right.
![2020-09-18_011627](https://user-images.githubusercontent.com/23090085/93505768-ddf76f00-f94d-11ea-8b05-28f40e53d384.jpg)

Solution, maybe you can add "SingleChildScrollView" because you use multiple "Padding".
![2020-09-18_011946](https://user-images.githubusercontent.com/23090085/93505795-e6e84080-f94d-11ea-9488-bce396693e2b.jpg)

**Comment by relf108** [comment]
This is a small bug in the example app rather than the actual API and isn't really a high priority for now. If you would like to make a pull request fixing this issue that would be much appreciated.
