### ISSUE TITLE
Gitbook seems not to be Free

### ISSUE THREAD

**Issue by Larpoux** [bsutton/sounds#45]
Sounds uses Gitbook for its documentation.
The result is a documentation which is really clean and very usable.
I did not know this tool but I am now impressed by it.

But Gitbook **does not seem to be free nor Open Source**. This is really bad. Very bad for documenting a Free Software.
For me this is a crippling drawback and I suggest to look to others Free and Open Source alternatives.

**Comment by relf108** [comment]
Git book kindly makes their software free for open source projects and as a quality product, I see no issue in charging businesses for it, nor us making use of it. Either way, this does not affect the sounds API.
