### ISSUE TITLE
Unable to instantiate unique MediaFormat with parameters [BUG]

### ISSUE THREAD

**Issue by handofthecode** [bsutton/sounds#51]
## Sounds Version : 

  sounds: 1.0.0-beta.5 & sounds: 0.9.3

----------------------------------------------------------

## Severity

- Result is not what expected

--------------------------------------------------------

## Platforms you faced the error 

- iOS & Android
- Real device

----------------------------------------------

```
var mediaFormat = AdtsAacMediaFormat(
      sampleRate: 44100,
      numChannels: 1,
      bitRate: 192000,
    );

print("mediaFormat: ${mediaFormat.bitRate}, ${mediaFormat.sampleRate}");
```

-Prints-

`mediaFormat: 16000, 16000`

Maybe I'm missing something?

**Comment by bsutton** [comment]
I believe the latest beta had a fix for this.

**Comment by bsutton** [comment]
Fixed.
