### ISSUE TITLE
[HELP] -- Why is iOS ObjectiveC code released and not the Swift code?

### ISSUE THREAD

**Issue by bardram** [bsutton/sounds#53]
I need Help for : 

**Understanding why there is a difference between the master branch and pub.dev release?**

-------------------------------------
## Here is my question :

In the `SoundPlayer.m` file line 44 there is an

```
assert (soundPlayerManager == nil);
```

which **fails**. 

Similar in the `SoundRecorder.m`.

And, I wanted to fix this (by simply removing these assert statements).

**HOWEVER** - when trying to clone and make a pull request of the Sounds github, the implementation on iOS is now done in Swift files.....

Why is the Swift version not released to pub.dev and available?

...or, the ObjectiveC version available for a PR?

Thanks.

**Comment by bsutton** [comment]
We are in the process of converting the code base to using ffi.

A such we don't expect to ever release the Swift code.

Ffi will allow us to ship sounds with essentially zero native code.

We have really only gotten seriously into this over the last couple of days and expect it will take a couple of weeks to get everything working.

You can monitor progress on the pigeon branch.

**Comment by bsutton** [comment]
For the 1.0.0 released we have delayed the ffi work. All code is now in the published repo.
