### ISSUE TITLE
"sounds_lite" package does not exist

### ISSUE THREAD

**Issue by Adam-Langley** [bsutton/sounds#55]
The documentation provides instructions for installing "sounds_lite" from pub.dev.
This does not work, however, as no such package has been published.

**Comment by bsutton** [comment]
The concept of sounds_lite has been removed.

If you like 'sounds' is the lite version of the product.

Our intent is to create a secondary repository called sounds_codec that adds back in things such as mp3 support.

You use Sounds for all of the core features and then add the sounds_codec library (which doesn't yet exists) to add in some of the heavier weight codecs.

We may even split this further depending on how large each codec is and how much code they use in common.

**Comment by bsutton** [comment]
Where did you find the reference to sounds_lite as its not in the current code base.

**Comment by Adam-Langley** [comment]
Hi @bsutton you're right - perhaps I had stumbled onto a readme.md from a previous version via google. I cannot find the documentation anymore.
If so, sorry about the noise.
