### ISSUE TITLE
[HELP] [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: 'package:sounds/src/sound_player.dart': Failed assertion: line 309 pos 12: 'track != null': is not true.

### ISSUE THREAD

**Issue by farahfarah1** [bsutton/sounds#66]
## Sounds Version : 

- **Released** or **Beta** version ?

- Version number ?

- **FULL** or **LITE** flavor ?

----------------------------------------------------------

## Severity

- Crash ?

- Result is not what expected ?

- Cannot build my App ?

- Minor issue ?

--------------------------------------------------------

## Platforms you faced the error 

- iOS ?

- Android ?

- Both ?

- Emulator ? 

- Real device ?

----------------------------------------------

## Logs
(This is very important. Most of the time we cannot do anything if we do not have information on your bug)

-----------------------------------------------

## flutter doctor :

-----------------------------------------------

## flutter pub deps :

------------------------------------------------

##  Screenshots

(If applicable, add screenshots to help explain your problem).

-----------------------------------------------------

**Describe the bug**

**To Reproduce**

**Expected behavior**

-----------------------------------------------------------------

**Comment by bsutton** [comment]
Fixed in 1.0.0
