### ISSUE TITLE
Please Help!!!

### ISSUE THREAD

**Issue by pandeytanuj01** [bsutton/sounds#7]
I need Help for :

In Track.fromFile() constructor whatever path i specify it says that the given path does not exist. I need to know how to specify the path of the track file. Please Help me with this @bsutton.

**Comment by bsutton** [comment]
The has  to be a path on the phones is.

You probably want to use track.fromAsset.

**Comment by kbanta11** [comment]
I was getting this as well trying to start a recording. It looks like if you are trying to record, you can't specify a path to record the file to if it doesn't already exist, I had to create a `Track.tempFile()` to get a path to a temp file to record to and then use that path in my `Track.fromFile(Track.tempFile())` to start the recording (a little bit different than the README tutorial, not sure if this is expect? Might be worth adding this step to the README if it is intended)

**Comment by bsutton** [comment]
Thanks for the feedback.
Yes you must create the file first.
I'm in the prices of updating the dock and elk make a note of the requirement.

**Comment by bsutton** [comment]
I've just push some additional doco on Sounds.
Its not complete but it should provide some additional information on using the api.

https://github.com/bsutton/sounds/wiki
